import { useEffect, useState } from "react";
import PageShell from "../../components/PageShell/PageShell";
import { useApp } from "../../context/AppContext";
import { useAuth } from "../../context/AuthContext";
import { Link, navigate } from "../../utils/router";
import "../SimplePages.css";

export default function Register(){
    const { translations:t } = useApp();
    const {user, register, loginGoogle, startPhoneSignIn, confirmPhoneCode, authError, firebaseConfigured} = useAuth();
    const [method,setMethod]=useState("email");
    useEffect(() => { if (user) navigate(user.role === "admin" ? "/admin" : "/account"); }, [user]); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [phone,setPhone]=useState(""); const [code,setCode]=useState(""); const [codeSent,setCodeSent]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
    const submitEmail=async e=>{e.preventDefault();setError("");setMessage("");setBusy(true);try{await register(name,email,password);setMessage(t.account.emailVerificationNotice);}catch(err){setError(err.message)}finally{setBusy(false)}};
    const submitPhone=async e=>{e.preventDefault();setError("");setMessage("");setBusy(true);try{if(!codeSent){await startPhoneSignIn(phone);setCodeSent(true)}else{const u=await confirmPhoneCode(code,name);if(u.role!=="client"){setError(t.account.clientOnly);return}navigate("/account")}}catch(err){setError(err.message)}finally{setBusy(false)}};
    const google=async()=>{setError("");setBusy(true);try{const user=await loginGoogle();if(!user)return;if(user.role!=="client")throw new Error(t.account.clientOnly);navigate("/account")}catch(err){setError(err.message)}finally{setBusy(false)}};
    return <PageShell><section className="page-section"><div className="container" style={{maxWidth:700}}><article className="info-card auth-modern-card">
        <span className="page-hero__eyebrow">{t.account.createAccount}</span><h1>{t.account.createAccount}</h1><p>{t.account.registerDescription}</p>{(!firebaseConfigured || authError) && <div className="auth-error auth-error--setup">{authError || "Firebase Authentication is not configured. Add your Firebase Web App settings to frontend/.env.local before using Google or SMS authentication."}</div>}
        <div className="auth-provider-grid"><button type="button" className="auth-provider auth-provider--google" disabled={busy} onClick={google}><span>G</span> {t.account.continueGoogle}</button><button type="button" className={`auth-provider ${method === "phone" ? "is-active" : ""}`} disabled={busy} onClick={()=>{setMethod("phone");setError("")}}><span>⌕</span> {t.account.continuePhone}</button></div>
        <div className="auth-tabs"><button type="button" className={method === "email"?"is-active":""} onClick={()=>setMethod("email")}>{t.account.email}</button><button type="button" className={method === "phone"?"is-active":""} onClick={()=>setMethod("phone")}>{t.account.phone}</button></div>
        {method === "email" ? <form className="simple-form" onSubmit={submitEmail}><label>{t.account.fullName}<input value={name} onChange={e=>setName(e.target.value)} required autoComplete="name" /></label><label>{t.account.email}<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" /></label><label>{t.account.password}<input type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} required autoComplete="new-password" /></label>{error&&<p className="auth-error">{error}</p>}{message&&<p className="auth-success">{message}</p>}<button type="submit" disabled={busy}>{busy?t.account.creating:t.account.createAccount}</button></form> : <form className="simple-form" onSubmit={submitPhone}><label>{t.account.fullName}<input value={name} onChange={e=>setName(e.target.value)} required autoComplete="name" /></label><label>{t.account.phone}<input type="tel" placeholder="+1 555 123 4567" value={phone} onChange={e=>setPhone(e.target.value)} required autoComplete="tel" /></label>{codeSent&&<label>{t.account.verificationCode}<input inputMode="numeric" maxLength={6} value={code} onChange={e=>setCode(e.target.value)} required autoComplete="one-time-code" /></label>}<div id="recaptcha-container" />{error&&<p className="auth-error">{error}</p>}<button type="submit" disabled={busy}>{busy?(codeSent?t.account.verifying:t.account.sending):(codeSent?t.account.verifyCreate:t.account.sendCode)}</button></form>}
        <p style={{marginTop:20}}>{t.account.alreadyAccount} <Link to="/sign-in" className="text-link">{t.account.signIn}</Link></p>
    </article></div></section></PageShell>
}
