import priusImage from "./assets/vehicles/prius.webp";
import rav4Image from "./assets/vehicles/rav4.webp";
import corollaImage from "./assets/vehicles/corolla.webp";
import camryImage from "./assets/vehicles/camry.webp";
import highlanderImage from "./assets/vehicles/highlander.webp";
import siennaImage from "./assets/vehicles/sienna.webp";

export const vehicles = [
    {
        id: "VH-001",
        slug: "toyota-prius",
        name: "Toyota Prius",
        shortName: "PRIUS",
        category: "compact",
        categoryLabel: "Hybrid",
        price: 59,
        seats: 5,
        luggage: 2,
        transmission: "Automatic",
        efficiency: "57 MPG",
        color: "Silver",
        status: "Available",
        image: priusImage,
        imageUrl: "",
        accent: "green",
    },
    {
        id: "VH-002",
        slug: "toyota-rav4",
        name: "Toyota RAV4",
        shortName: "RAV4",
        category: "suv",
        categoryLabel: "SUV",
        price: 79,
        seats: 5,
        luggage: 3,
        transmission: "Automatic",
        efficiency: "29 MPG",
        color: "Ice Cap",
        status: "Available",
        image: rav4Image,
        imageUrl: "",
        accent: "green",
    },
    {
        id: "VH-003",
        slug: "toyota-corolla",
        name: "Toyota Corolla",
        shortName: "COROLLA",
        category: "compact",
        categoryLabel: "Compact Hybrid",
        price: 59,
        seats: 5,
        luggage: 2,
        transmission: "Automatic",
        efficiency: "50 MPG",
        color: "Graphite",
        status: "Available",
        image: corollaImage,
        imageUrl: "",
        accent: "green",
    },
    {
        id: "VH-004",
        slug: "toyota-camry",
        name: "Toyota Camry",
        shortName: "CAMRY",
        category: "sedan",
        categoryLabel: "Premium Sedan",
        price: 69,
        seats: 5,
        luggage: 3,
        transmission: "Automatic",
        efficiency: "47 MPG",
        color: "Pearl White",
        status: "Available",
        image: camryImage,
        imageUrl: "",
        accent: "green",
    },
    {
        id: "VH-005",
        slug: "toyota-highlander",
        name: "Toyota Highlander",
        shortName: "HIGHLANDER",
        category: "suv",
        categoryLabel: "Three-Row SUV",
        price: 104,
        seats: 7,
        luggage: 4,
        transmission: "Automatic",
        efficiency: "24 MPG",
        color: "Ice Cap",
        status: "Available",
        image: highlanderImage,
        imageUrl: "",
        accent: "purple",
    },
    {
        id: "VH-006",
        slug: "toyota-sienna",
        name: "Toyota Sienna",
        shortName: "SIENNA",
        category: "premium",
        categoryLabel: "Hybrid Minivan",
        price: 99,
        seats: 7,
        luggage: 5,
        transmission: "Automatic",
        efficiency: "36 MPG",
        color: "Blueprint",
        status: "Available",
        image: siennaImage,
        imageUrl: "",
        accent: "purple",
    },
];
